// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI agent that generates blog post ideas based on a topic and target audience.
 *
 * - generateBlogIdeas - A function that generates blog post ideas.
 * - GenerateBlogIdeasInput - The input type for the generateBlogIdeas function.
 * - GenerateBlogIdeasOutput - The return type for the generateBlogIdeas function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBlogIdeasInputSchema = z.object({
  topic: z.string().describe('A broad topic or industry (e.g., sustainable living, digital marketing trends).'),
  targetAudience: z.string().optional().describe('Target audience (e.g., beginners, small businesses).'),
});
export type GenerateBlogIdeasInput = z.infer<typeof GenerateBlogIdeasInputSchema>;

const BlogIdeaSchema = z.object({
  title: z.string().describe('A unique and engaging blog post title.'),
  outline: z.string().describe('A brief (1-2 sentence) outline of the blog post.'),
});

const GenerateBlogIdeasOutputSchema = z.array(BlogIdeaSchema).length(5)
export type GenerateBlogIdeasOutput = z.infer<typeof GenerateBlogIdeasOutputSchema>;

export async function generateBlogIdeas(input: GenerateBlogIdeasInput): Promise<GenerateBlogIdeasOutput> {
  return generateBlogIdeasFlow(input);
}

const generateBlogIdeasPrompt = ai.definePrompt({
  name: 'generateBlogIdeasPrompt',
  input: {schema: GenerateBlogIdeasInputSchema},
  output: {schema: GenerateBlogIdeasOutputSchema},
  prompt: `You are an expert blog post idea generator.

  Generate 5 unique and SEO-friendly blog post titles and brief outlines for the topic: {{topic}}. Target audience: {{targetAudience}}. Ensure variety and an engaging tone.

  Return a JSON array of 5 blog post ideas. Each object in the array should have a title and an outline.
  The "title" field should contain the title of the blog post.
  The "outline" field should contain a brief (1-2 sentence) outline of the blog post.
  `,
});

const generateBlogIdeasFlow = ai.defineFlow(
  {
    name: 'generateBlogIdeasFlow',
    inputSchema: GenerateBlogIdeasInputSchema,
    outputSchema: GenerateBlogIdeasOutputSchema,
  },
  async input => {
    const {output} = await generateBlogIdeasPrompt(input);
    return output!;
  }
);
